<a href="https://colab.research.google.com/github/SanjaraT/Breast-Cancer-Classification-with-PyTorch/blob/main/Breast_Cancer_NN(PyToch)ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
column_names = [
    'id', 'diagnosis',
    'radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean', 'smoothness_mean',
    'compactness_mean', 'concavity_mean', 'concave_points_mean', 'symmetry_mean', 'fractal_dimension_mean',
    'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
    'compactness_se', 'concavity_se', 'concave_points_se', 'symmetry_se', 'fractal_dimension_se',
    'radius_worst', 'texture_worst', 'perimeter_worst', 'area_worst', 'smoothness_worst',
    'compactness_worst', 'concavity_worst', 'concave_points_worst', 'symmetry_worst', 'fractal_dimension_worst'
]

In [3]:
df = pd.read_csv("/content/drive/MyDrive/wdbc.data",header=None, names = column_names)

In [ ]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
df.shape

(569, 32)

In [ ]:
df.dtypes

id                           int64
diagnosis                   object
radius_mean                float64
texture_mean               float64
perimeter_mean             float64
area_mean                  float64
smoothness_mean            float64
compactness_mean           float64
concavity_mean             float64
concave_points_mean        float64
symmetry_mean              float64
fractal_dimension_mean     float64
radius_se                  float64
texture_se                 float64
perimeter_se               float64
area_se                    float64
smoothness_se              float64
compactness_se             float64
concavity_se               float64
concave_points_se          float64
symmetry_se                float64
fractal_dimension_se       float64
radius_worst               float64
texture_worst              float64
perimeter_worst            float64
area_worst                 float64
smoothness_worst           float64
compactness_worst          float64
concavity_worst            float64
concave_points_worst       float64
symmetry_worst             float64
fractal_dimension_worst    float64
dtype: object

In [4]:
df.drop(columns=['id'], inplace=True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
#Summary statics
df.isnull().sum()
# df.duplicated().sum()

diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave_points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave_points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave_points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [ ]:
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [5]:
#Feature/Target
X = df.drop(['diagnosis'],axis=1)
y = df['diagnosis']

In [6]:
# Train Test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [7]:
# Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[ 0.51855873,  0.89182579,  0.4246317 , ..., -0.23574392,
         0.05456632,  0.02183673],
       [-0.51636409, -1.63971029, -0.54134872, ..., -0.32320788,
        -0.13757624, -0.90440164],
       [-0.36811839,  0.45551496, -0.38824993, ..., -0.89082504,
        -0.675893  , -0.14401559],
       ...,
       [-0.32616206,  1.33280304, -0.38905998, ..., -0.84289958,
        -0.96490082, -1.16888375],
       [ 0.00948859,  0.25952507,  0.00786279, ...,  0.27571059,
        -0.60284707, -0.30545988],
       [ 0.80945595,  0.36918608,  0.79320285, ...,  1.00657384,
        -0.46151907, -0.44817001]])

In [ ]:
y_train

10     M
170    B
407    B
430    M
27     M
      ..
37     B
415    B
458    B
476    B
335    M
Name: diagnosis, Length: 455, dtype: object

In [8]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [ ]:
y_train

array([1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [9]:
# Arrays to tensors
import torch

X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor

tensor([1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
        1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
        0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
        0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
        1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
        1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
        1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
        1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [10]:
# Custom dataset
from torch.utils.data import Dataset, DataLoader

In [20]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [21]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [22]:
#  Dataloader

train_dataloader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_dataloader = DataLoader(test_dataset,batch_size=32, shuffle=True)

# Defining the model

In [23]:
import torch.nn as nn
class NN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, X):
    out = self.linear(X)
    out = self.sigmoid(out)
    return out

In [24]:
# Parameters
lr = 0.1
epochs = 50

In [25]:
# loss function
loss_fun = nn.BCELoss()

# Training

In [26]:
# Build Model
model = NN(X_train_tensor.shape[1])

# Optimization
optimizer = torch.optim.SGD(model.parameters(), lr=lr)

for e in range(epochs):
  for batch_features, batch_labels in train_dataloader:
    # forward pass
    y_pred = model(X_train_tensor)
    # print(y_pred)

    #Loss
    loss = loss_fun(y_pred, y_train_tensor.view(-1,1))

    # optimizer
    optimizer.zero_grad()

    # bacwardpass
    loss.backward()

    # parameters update
    optimizer.step()

    # gradients
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()

    # print loss
    print(f'Epoch: {e+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6172195672988892
Epoch: 1, Loss: 0.4895520508289337
Epoch: 1, Loss: 0.41643279790878296
Epoch: 1, Loss: 0.3689543604850769
Epoch: 1, Loss: 0.3353084325790405
Epoch: 1, Loss: 0.3099699020385742
Epoch: 1, Loss: 0.2900288999080658
Epoch: 1, Loss: 0.2738090455532074
Epoch: 1, Loss: 0.26027557253837585
Epoch: 1, Loss: 0.24875405430793762
Epoch: 1, Loss: 0.23878519237041473
Epoch: 1, Loss: 0.23004461824893951
Epoch: 1, Loss: 0.22229625284671783
Epoch: 1, Loss: 0.2153637707233429
Epoch: 1, Loss: 0.20911237597465515
Epoch: 2, Loss: 0.20343729853630066
Epoch: 2, Loss: 0.19825530052185059
Epoch: 2, Loss: 0.19349956512451172
Epoch: 2, Loss: 0.18911553919315338
Epoch: 2, Loss: 0.18505820631980896
Epoch: 2, Loss: 0.18128997087478638
Epoch: 2, Loss: 0.17777912318706512
Epoch: 2, Loss: 0.17449872195720673
Epoch: 2, Loss: 0.17142561078071594
Epoch: 2, Loss: 0.16853974759578705
Epoch: 2, Loss: 0.1658237725496292
Epoch: 2, Loss: 0.16326239705085754
Epoch: 2, Loss: 0.16084223985671997
Epoch: 2, Loss: 0.158551424741745
Epoch: 2, Loss: 0.15637940168380737
Epoch: 3, Loss: 0.1543167382478714
Epoch: 3, Loss: 0.15235501527786255
Epoch: 3, Loss: 0.15048667788505554
Epoch: 3, Loss: 0.1487048715353012
Epoch: 3, Loss: 0.1470034420490265
Epoch: 3, Loss: 0.1453767865896225
Epoch: 3, Loss: 0.14381982386112213
Epoch: 3, Loss: 0.1423279047012329
Epoch: 3, Loss: 0.14089684188365936
Epoch: 3, Loss: 0.1395227611064911
Epoch: 3, Loss: 0.13820211589336395
Epoch: 3, Loss: 0.1369316726922989
Epoch: 3, Loss: 0.13570843636989594
Epoch: 3, Loss: 0.13452963531017303
Epoch: 3, Loss: 0.13339275121688843
Epoch: 4, Loss: 0.1322954297065735
Epoch: 4, Loss: 0.1312355250120163
Epoch: 4, Loss: 0.1302109956741333
Epoch: 4, Loss: 0.12921996414661407
Epoch: 4, Loss: 0.12826071679592133
Epoch: 4, Loss: 0.12733162939548492
Epoch: 4, Loss: 0.1264311969280243
Epoch: 4, Loss: 0.125558003783226
Epoch: 4, Loss: 0.12471075356006622
Epoch: 4, Loss: 0.12388820946216583
Epoch: 4, Loss: 0.12308923155069351
Epoch: 4, Loss: 0.12231272459030151
Epoch: 4, Loss: 0.12155771255493164
Epoch: 4, Loss: 0.12082318961620331
Epoch: 4, Loss: 0.12010829895734787
Epoch: 5, Loss: 0.11941219866275787
Epoch: 5, Loss: 0.11873410642147064
Epoch: 5, Loss: 0.1180732399225235
Epoch: 5, Loss: 0.11742892116308212
Epoch: 5, Loss: 0.11680047959089279
Epoch: 5, Loss: 0.11618728935718536
Epoch: 5, Loss: 0.11558874696493149
Epoch: 5, Loss: 0.11500430107116699
Epoch: 5, Loss: 0.1144334152340889
Epoch: 5, Loss: 0.11387555301189423
Epoch: 5, Loss: 0.11333028972148895
Epoch: 5, Loss: 0.11279711127281189
Epoch: 5, Loss: 0.112275630235672
Epoch: 5, Loss: 0.11176539212465286
Epoch: 5, Loss: 0.11126601696014404
Epoch: 6, Loss: 0.11077714711427689
Epoch: 6, Loss: 0.11029843240976334
Epoch: 6, Loss: 0.10982947796583176
Epoch: 6, Loss: 0.10937003791332245
Epoch: 6, Loss: 0.10891975462436676
Epoch: 6, Loss: 0.10847830772399902
Epoch: 6, Loss: 0.10804546624422073
Epoch: 6, Loss: 0.10762093216180801
Epoch: 6, Loss: 0.10720445960760117
Epoch: 6, Loss: 0.1067957878112793
Epoch: 6, Loss: 0.1063946932554245
Epoch: 6, Loss: 0.10600093007087708
Epoch: 6, Loss: 0.1056143119931221
Epoch: 6, Loss: 0.10523458570241928
Epoch: 6, Loss: 0.10486158728599548
Epoch: 7, Loss: 0.1044950857758522
Epoch: 7, Loss: 0.1041349470615387
Epoch: 7, Loss: 0.10378095507621765
Epoch: 7, Loss: 0.10343294590711594
Epoch: 7, Loss: 0.10309074819087982
Epoch: 7, Loss: 0.10275422781705856
Epoch: 7, Loss: 0.10242321342229843
Epoch: 7, Loss: 0.10209755599498749
Epoch: 7, Loss: 0.10177712887525558
Epoch: 7, Loss: 0.10146177560091019
Epoch: 7, Loss: 0.10115139931440353
Epoch: 7, Loss: 0.10084584355354309
Epoch: 7, Loss: 0.10054497420787811
Epoch: 7, Loss: 0.10024870187044144
Epoch: 7, Loss: 0.09995690733194351
Epoch: 8, Loss: 0.09966946393251419
Epoch: 8, Loss: 0.09938626736402512
Epoch: 8, Loss: 0.09910724312067032
Epoch: 8, Loss: 0.09883226454257965
Epoch: 8, Loss: 0.09856124967336655
Epoch: 8, Loss: 0.09829409420490265
Epoch: 8, Loss: 0.0980307087302208
Epoch: 8, Loss: 0.09777101129293442
Epoch: 8, Loss: 0.09751492738723755
Epoch: 8, Loss: 0.09726235270500183
Epoch: 8, Loss: 0.09701322764158249
Epoch: 8, Loss: 0.09676746279001236
Epoch: 8, Loss: 0.09652499854564667
Epoch: 8, Loss: 0.09628573060035706
Epoch: 8, Loss: 0.09604964405298233
Epoch: 9, Loss: 0.09581661224365234
Epoch: 9, Loss: 0.09558660537004471
Epoch: 9, Loss: 0.09535954892635345
Epoch: 9, Loss: 0.09513538330793381
Epoch: 9, Loss: 0.0949140265583992
Epoch: 9, Loss: 0.09469546377658844
Epoch: 9, Loss: 0.09447960555553436
Epoch: 9, Loss: 0.09426639974117279
Epoch: 9, Loss: 0.09405581653118134
Epoch: 9, Loss: 0.09384777396917343
Epoch: 9, Loss: 0.09364224225282669
Epoch: 9, Loss: 0.09343914687633514
Epoch: 9, Loss: 0.0932384580373764
Epoch: 9, Loss: 0.09304013848304749
Epoch: 9, Loss: 0.09284412115812302
Epoch: 10, Loss: 0.09265037626028061
Epoch: 10, Loss: 0.09245885163545609
Epoch: 10, Loss: 0.09226950258016586
Epoch: 10, Loss: 0.09208231419324875
Epoch: 10, Loss: 0.09189721196889877
Epoch: 10, Loss: 0.09171417355537415
Epoch: 10, Loss: 0.09153317660093307
Epoch: 10, Loss: 0.09135415405035019
Epoch: 10, Loss: 0.0911770835518837
Epoch: 10, Loss: 0.09100193530321121
Epoch: 10, Loss: 0.09082867950201035
Epoch: 10, Loss: 0.09065726399421692
Epoch: 10, Loss: 0.09048765152692795
Epoch: 10, Loss: 0.09031984210014343
Epoch: 10, Loss: 0.090153768658638
Epoch: 11, Loss: 0.08998944610357285
Epoch: 11, Loss: 0.089826799929142
Epoch: 11, Loss: 0.08966581523418427
Epoch: 11, Loss: 0.08950647711753845
Epoch: 11, Loss: 0.08934875577688217
Epoch: 11, Loss: 0.08919259905815125
Epoch: 11, Loss: 0.08903802931308746
Epoch: 11, Loss: 0.08888497203588486
Epoch: 11, Loss: 0.08873341232538223
Epoch: 11, Loss: 0.0885833352804184
Epoch: 11, Loss: 0.08843472599983215
Epoch: 11, Loss: 0.08828755468130112
Epoch: 11, Loss: 0.0881417915225029
Epoch: 11, Loss: 0.08799741417169571
Epoch: 11, Loss: 0.08785440027713776
Epoch: 12, Loss: 0.08771274238824844
Epoch: 12, Loss: 0.08757240325212479
Epoch: 12, Loss: 0.08743337541818619
Epoch: 12, Loss: 0.08729562163352966
Epoch: 12, Loss: 0.08715913444757462
Epoch: 12, Loss: 0.08702389150857925
Epoch: 12, Loss: 0.08688988536596298
Epoch: 12, Loss: 0.08675707876682281
Epoch: 12, Loss: 0.08662545680999756
Epoch: 12, Loss: 0.08649500459432602
Epoch: 12, Loss: 0.0863657221198082
Epoch: 12, Loss: 0.08623757213354111
Epoch: 12, Loss: 0.08611053973436356
Epoch: 12, Loss: 0.08598461747169495
Epoch: 12, Loss: 0.08585978299379349
Epoch: 13, Loss: 0.08573601394891739
Epoch: 13, Loss: 0.08561331033706665
Epoch: 13, Loss: 0.08549164235591888
Epoch: 13, Loss: 0.0853710025548935
Epoch: 13, Loss: 0.08525138348340988
Epoch: 13, Loss: 0.08513277769088745
Epoch: 13, Loss: 0.08501513302326202
Epoch: 13, Loss: 0.08489847183227539
Epoch: 13, Loss: 0.08478277176618576
Epoch: 13, Loss: 0.08466801047325134
Epoch: 13, Loss: 0.08455417305231094
Epoch: 13, Loss: 0.08444125950336456
Epoch: 13, Loss: 0.0843292623758316
Epoch: 13, Loss: 0.08421815931797028
Epoch: 13, Loss: 0.08410793542861938
Epoch: 14, Loss: 0.08399858325719833
Epoch: 14, Loss: 0.08389010280370712
Epoch: 14, Loss: 0.08378245681524277
Epoch: 14, Loss: 0.08367564529180527
Epoch: 14, Loss: 0.08356968313455582
Epoch: 14, Loss: 0.08346451818943024
Epoch: 14, Loss: 0.08336016535758972
Epoch: 14, Loss: 0.08325659483671188
Epoch: 14, Loss: 0.08315382152795792
Epoch: 14, Loss: 0.08305183053016663
Epoch: 14, Loss: 0.08295059204101562
Epoch: 14, Loss: 0.08285012096166611
Epoch: 14, Loss: 0.08275038003921509
Epoch: 14, Loss: 0.08265138417482376
Epoch: 14, Loss: 0.08255311101675034
Epoch: 15, Loss: 0.08245556801557541
Epoch: 15, Loss: 0.082358717918396
Epoch: 15, Loss: 0.08226259052753448
Epoch: 15, Loss: 0.0821671262383461
Epoch: 15, Loss: 0.08207238465547562
Epoch: 15, Loss: 0.08197829872369766
Epoch: 15, Loss: 0.08188486844301224
Epoch: 15, Loss: 0.08179212361574173
Epoch: 15, Loss: 0.08170001208782196
Epoch: 15, Loss: 0.08160855621099472
Epoch: 15, Loss: 0.08151773363351822
Epoch: 15, Loss: 0.08142752945423126
Epoch: 15, Loss: 0.08133795857429504
Epoch: 15, Loss: 0.08124901354312897
Epoch: 15, Loss: 0.08116064965724945
Epoch: 16, Loss: 0.08107289671897888
Epoch: 16, Loss: 0.08098574727773666
Epoch: 16, Loss: 0.080899178981781
Epoch: 16, Loss: 0.08081318438053131
Epoch: 16, Loss: 0.08072777837514877
Epoch: 16, Loss: 0.08064292371273041
Epoch: 16, Loss: 0.080558642745018
Epoch: 16, Loss: 0.08047491312026978
Epoch: 16, Loss: 0.08039173483848572
Epoch: 16, Loss: 0.08030908554792404
Epoch: 16, Loss: 0.08022698014974594
Epoch: 16, Loss: 0.08014540374279022
Epoch: 16, Loss: 0.08006436377763748
Epoch: 16, Loss: 0.07998383045196533
Epoch: 16, Loss: 0.07990381121635437
Epoch: 17, Loss: 0.079824298620224
Epoch: 17, Loss: 0.07974530011415482
Epoch: 17, Loss: 0.07966678589582443
Epoch: 17, Loss: 0.07958877086639404
Epoch: 17, Loss: 0.07951123267412186
Epoch: 17, Loss: 0.07943418622016907
Epoch: 17, Loss: 0.07935761660337448
Epoch: 17, Loss: 0.0792815089225769
Epoch: 17, Loss: 0.07920587807893753
Epoch: 17, Loss: 0.07913070172071457
Epoch: 17, Loss: 0.07905598729848862
Epoch: 17, Loss: 0.07898171991109848
Epoch: 17, Loss: 0.07890789955854416
Epoch: 17, Loss: 0.07883452624082565
Epoch: 17, Loss: 0.07876158505678177
Epoch: 18, Loss: 0.0786890834569931
Epoch: 18, Loss: 0.07861701399087906
Epoch: 18, Loss: 0.07854535430669785
Epoch: 18, Loss: 0.07847413420677185
Epoch: 18, Loss: 0.07840332388877869
Epoch: 18, Loss: 0.07833292335271835
Epoch: 18, Loss: 0.07826292514801025
Epoch: 18, Loss: 0.07819333672523499
Epoch: 18, Loss: 0.07812415063381195
Epoch: 18, Loss: 0.07805535942316055
Epoch: 18, Loss: 0.07798696309328079
Epoch: 18, Loss: 0.07791895419359207
Epoch: 18, Loss: 0.07785133272409439
Epoch: 18, Loss: 0.07778408378362656
Epoch: 18, Loss: 0.07771720737218857
Epoch: 19, Loss: 0.07765072584152222
Epoch: 19, Loss: 0.07758460193872452
Epoch: 19, Loss: 0.07751884311437607
Epoch: 19, Loss: 0.07745345681905746
Epoch: 19, Loss: 0.07738842070102692
Epoch: 19, Loss: 0.07732374221086502
Epoch: 19, Loss: 0.07725942134857178
Epoch: 19, Loss: 0.07719545811414719
Epoch: 19, Loss: 0.07713183015584946
Epoch: 19, Loss: 0.07706853747367859
Epoch: 19, Loss: 0.07700559496879578
Epoch: 19, Loss: 0.07694298774003983
Epoch: 19, Loss: 0.07688072323799133
Epoch: 19, Loss: 0.07681877166032791
Epoch: 19, Loss: 0.07675717025995255
Epoch: 20, Loss: 0.07669587433338165
Epoch: 20, Loss: 0.07663490623235703
Epoch: 20, Loss: 0.07657425105571747
Epoch: 20, Loss: 0.07651393115520477
Epoch: 20, Loss: 0.07645390182733536
Epoch: 20, Loss: 0.07639420032501221
Epoch: 20, Loss: 0.07633479684591293
Epoch: 20, Loss: 0.07627569884061813
Epoch: 20, Loss: 0.0762169137597084
Epoch: 20, Loss: 0.07615842670202255
Epoch: 20, Loss: 0.07610021531581879
Epoch: 20, Loss: 0.07604231685400009
Epoch: 20, Loss: 0.07598471641540527
Epoch: 20, Loss: 0.07592739164829254
Epoch: 20, Loss: 0.07587035745382309
Epoch: 21, Loss: 0.07581360638141632
Epoch: 21, Loss: 0.07575714588165283
Epoch: 21, Loss: 0.07570094615221024
Epoch: 21, Loss: 0.07564503699541092
Epoch: 21, Loss: 0.07558940351009369
Epoch: 21, Loss: 0.07553403079509735
Epoch: 21, Loss: 0.0754789412021637
Epoch: 21, Loss: 0.07542411237955093
Epoch: 21, Loss: 0.07536954432725906
Epoch: 21, Loss: 0.07531525939702988
Epoch: 21, Loss: 0.07526122033596039
Epoch: 21, Loss: 0.0752074345946312
Epoch: 21, Loss: 0.0751539096236229
Epoch: 21, Loss: 0.07510065287351608
Epoch: 21, Loss: 0.07504763454198837
Epoch: 22, Loss: 0.07499487698078156
Epoch: 22, Loss: 0.07494235783815384
Epoch: 22, Loss: 0.07489008456468582
Epoch: 22, Loss: 0.0748380571603775
Epoch: 22, Loss: 0.07478629052639008
Epoch: 22, Loss: 0.07473473995923996
Epoch: 22, Loss: 0.07468343526124954
Epoch: 22, Loss: 0.07463236898183823
Epoch: 22, Loss: 0.07458154112100601
Epoch: 22, Loss: 0.0745309442281723
Epoch: 22, Loss: 0.0744805783033371
Epoch: 22, Loss: 0.0744304358959198
Epoch: 22, Loss: 0.07438052445650101
Epoch: 22, Loss: 0.07433084398508072
Epoch: 22, Loss: 0.07428137958049774
Epoch: 23, Loss: 0.07423213869333267
Epoch: 23, Loss: 0.07418312132358551
Epoch: 23, Loss: 0.07413431257009506
Epoch: 23, Loss: 0.07408572733402252
Epoch: 23, Loss: 0.07403736561536789
Epoch: 23, Loss: 0.07398920506238937
Epoch: 23, Loss: 0.07394126057624817
Epoch: 23, Loss: 0.07389352470636368
Epoch: 23, Loss: 0.0738460049033165
Epoch: 23, Loss: 0.07379867881536484
Epoch: 23, Loss: 0.07375156879425049
Epoch: 23, Loss: 0.07370465993881226
Epoch: 23, Loss: 0.07365795224905014
Epoch: 23, Loss: 0.07361145317554474
Epoch: 23, Loss: 0.07356515526771545
Epoch: 24, Loss: 0.07351904362440109
Epoch: 24, Loss: 0.07347314059734344
Epoch: 24, Loss: 0.07342741638422012
Epoch: 24, Loss: 0.07338190078735352
Epoch: 24, Loss: 0.07333655655384064
Epoch: 24, Loss: 0.07329142093658447
Epoch: 24, Loss: 0.07324647158384323
Epoch: 24, Loss: 0.07320170849561691
Epoch: 24, Loss: 0.07315712422132492
Epoch: 24, Loss: 0.07311274111270905
Epoch: 24, Loss: 0.0730685219168663
Epoch: 24, Loss: 0.07302450388669968
Epoch: 24, Loss: 0.07298065721988678
Epoch: 24, Loss: 0.0729369968175888
Epoch: 24, Loss: 0.07289350032806396
Epoch: 25, Loss: 0.07285019755363464
Epoch: 25, Loss: 0.07280706614255905
Epoch: 25, Loss: 0.07276409864425659
Epoch: 25, Loss: 0.07272131741046906
Epoch: 25, Loss: 0.07267870754003525
Epoch: 25, Loss: 0.07263626158237457
Epoch: 25, Loss: 0.07259399443864822
Epoch: 25, Loss: 0.07255188375711441
Epoch: 25, Loss: 0.07250995934009552
Epoch: 25, Loss: 0.07246818393468857
Epoch: 25, Loss: 0.07242657989263535
Epoch: 25, Loss: 0.07238514721393585
Epoch: 25, Loss: 0.0723438709974289
Epoch: 25, Loss: 0.07230275124311447
Epoch: 25, Loss: 0.07226179540157318
Epoch: 26, Loss: 0.07222100347280502
Epoch: 26, Loss: 0.0721803680062294
Epoch: 26, Loss: 0.07213988155126572
Epoch: 26, Loss: 0.07209956645965576
Epoch: 26, Loss: 0.07205939292907715
Epoch: 26, Loss: 0.07201938331127167
Epoch: 26, Loss: 0.07197951525449753
Epoch: 26, Loss: 0.07193979620933533
Epoch: 26, Loss: 0.07190025597810745
Epoch: 26, Loss: 0.07186084240674973
Epoch: 26, Loss: 0.07182157784700394
Epoch: 26, Loss: 0.07178247720003128
Epoch: 26, Loss: 0.07174351811408997
Epoch: 26, Loss: 0.0717046856880188
Epoch: 26, Loss: 0.07166602462530136
Epoch: 27, Loss: 0.07162749022245407
Epoch: 27, Loss: 0.07158910483121872
Epoch: 27, Loss: 0.07155086100101471
Epoch: 27, Loss: 0.07151276618242264
Epoch: 27, Loss: 0.07147479802370071
Epoch: 27, Loss: 0.07143697142601013
Epoch: 27, Loss: 0.07139929383993149
Epoch: 27, Loss: 0.07136175036430359
Epoch: 27, Loss: 0.07132433354854584
Epoch: 27, Loss: 0.07128706574440002
Epoch: 27, Loss: 0.07124992460012436
Epoch: 27, Loss: 0.07121291756629944
Epoch: 27, Loss: 0.07117605209350586
Epoch: 27, Loss: 0.07113930583000183
Epoch: 27, Loss: 0.07110271602869034
Epoch: 28, Loss: 0.0710662230849266
Epoch: 28, Loss: 0.0710299015045166
Epoch: 28, Loss: 0.07099366933107376
Epoch: 28, Loss: 0.07095757871866226
Epoch: 28, Loss: 0.07092162221670151
Epoch: 28, Loss: 0.0708857849240303
Epoch: 28, Loss: 0.07085008174180984
Epoch: 28, Loss: 0.07081449776887894
Epoch: 28, Loss: 0.07077904045581818
Epoch: 28, Loss: 0.07074370235204697
Epoch: 28, Loss: 0.0707084983587265
Epoch: 28, Loss: 0.07067340612411499
Epoch: 28, Loss: 0.07063843309879303
Epoch: 28, Loss: 0.07060359418392181
Epoch: 28, Loss: 0.07056886702775955
Epoch: 29, Loss: 0.07053426653146744
Epoch: 29, Loss: 0.07049976289272308
Epoch: 29, Loss: 0.07046539336442947
Epoch: 29, Loss: 0.07043114304542542
Epoch: 29, Loss: 0.07039700448513031
Epoch: 29, Loss: 0.07036297023296356
Epoch: 29, Loss: 0.07032907009124756
Epoch: 29, Loss: 0.07029526680707932
Epoch: 29, Loss: 0.07026158273220062
Epoch: 29, Loss: 0.07022801786661148
Epoch: 29, Loss: 0.07019456475973129
Epoch: 29, Loss: 0.07016120851039886
Epoch: 29, Loss: 0.07012798637151718
Epoch: 29, Loss: 0.07009485363960266
Epoch: 29, Loss: 0.07006184756755829
Epoch: 30, Loss: 0.07002893835306168
Epoch: 30, Loss: 0.06999614089727402
Epoch: 30, Loss: 0.06996344774961472
Epoch: 30, Loss: 0.06993087381124496
Epoch: 30, Loss: 0.06989838927984238
Epoch: 30, Loss: 0.06986603140830994
Epoch: 30, Loss: 0.06983376294374466
Epoch: 30, Loss: 0.06980159878730774
Epoch: 30, Loss: 0.06976954638957977
Epoch: 30, Loss: 0.06973758339881897
Epoch: 30, Loss: 0.06970573961734772
Epoch: 30, Loss: 0.06967400014400482
Epoch: 30, Loss: 0.06964234262704849
Epoch: 30, Loss: 0.06961078941822052
Epoch: 30, Loss: 0.0695793554186821
Epoch: 31, Loss: 0.06954801082611084
Epoch: 31, Loss: 0.06951675564050674
Epoch: 31, Loss: 0.0694856122136116
Epoch: 31, Loss: 0.06945455819368362
Epoch: 31, Loss: 0.0694236159324646
Epoch: 31, Loss: 0.06939274817705154
Epoch: 31, Loss: 0.06936199218034744
Epoch: 31, Loss: 0.0693313330411911
Epoch: 31, Loss: 0.06930076330900192
Epoch: 31, Loss: 0.0692702904343605
Epoch: 31, Loss: 0.06923990696668625
Epoch: 31, Loss: 0.06920963525772095
Epoch: 31, Loss: 0.06917943060398102
Epoch: 31, Loss: 0.06914933770895004
Epoch: 31, Loss: 0.06911933422088623
Epoch: 32, Loss: 0.06908942013978958
Epoch: 32, Loss: 0.0690595880150795
Epoch: 32, Loss: 0.06902986764907837
Epoch: 32, Loss: 0.0690002292394638
Epoch: 32, Loss: 0.06897067278623581
Epoch: 32, Loss: 0.06894120573997498
Epoch: 32, Loss: 0.0689118281006813
Epoch: 32, Loss: 0.0688825473189354
Epoch: 32, Loss: 0.06885334849357605
Epoch: 32, Loss: 0.06882424652576447
Epoch: 32, Loss: 0.06879521161317825
Epoch: 32, Loss: 0.0687662810087204
Epoch: 32, Loss: 0.06873742491006851
Epoch: 32, Loss: 0.06870865821838379
Epoch: 32, Loss: 0.06867998093366623
Epoch: 33, Loss: 0.06865138560533524
Epoch: 33, Loss: 0.06862287223339081
Epoch: 33, Loss: 0.06859445571899414
Epoch: 33, Loss: 0.06856611371040344
Epoch: 33, Loss: 0.06853784620761871
Epoch: 33, Loss: 0.06850967556238174
Epoch: 33, Loss: 0.06848156452178955
Epoch: 33, Loss: 0.06845356523990631
Epoch: 33, Loss: 0.06842561811208725
Epoch: 33, Loss: 0.06839776039123535
Epoch: 33, Loss: 0.06836999207735062
Epoch: 33, Loss: 0.06834229826927185
Epoch: 33, Loss: 0.06831468641757965
Epoch: 33, Loss: 0.06828715652227402
Epoch: 33, Loss: 0.06825970113277435
Epoch: 34, Loss: 0.06823232024908066
Epoch: 34, Loss: 0.06820502877235413
Epoch: 34, Loss: 0.06817779690027237
Epoch: 34, Loss: 0.06815065443515778
Epoch: 34, Loss: 0.06812358647584915
Epoch: 34, Loss: 0.0680966004729271
Epoch: 34, Loss: 0.06806968152523041
Epoch: 34, Loss: 0.06804284453392029
Epoch: 34, Loss: 0.06801607459783554
Epoch: 34, Loss: 0.06798938661813736
Epoch: 34, Loss: 0.06796275824308395
Epoch: 34, Loss: 0.06793622672557831
Epoch: 34, Loss: 0.06790976226329803
Epoch: 34, Loss: 0.06788336485624313
Epoch: 34, Loss: 0.0678570419549942
Epoch: 35, Loss: 0.06783079355955124
Epoch: 35, Loss: 0.06780461966991425
Epoch: 35, Loss: 0.06777851283550262
Epoch: 35, Loss: 0.06775248050689697
Epoch: 35, Loss: 0.0677265152335167
Epoch: 35, Loss: 0.06770062446594238
Epoch: 35, Loss: 0.06767480075359344
Epoch: 35, Loss: 0.06764905154705048
Epoch: 35, Loss: 0.06762336939573288
Epoch: 35, Loss: 0.06759775429964066
Epoch: 35, Loss: 0.0675722137093544
Epoch: 35, Loss: 0.06754673272371292
Epoch: 35, Loss: 0.06752132624387741
Epoch: 35, Loss: 0.06749600172042847
Epoch: 35, Loss: 0.0674707293510437
Epoch: 36, Loss: 0.06744551658630371
Epoch: 36, Loss: 0.06742037832736969
Epoch: 36, Loss: 0.06739531457424164
Epoch: 36, Loss: 0.06737031042575836
Epoch: 36, Loss: 0.06734538078308105
Epoch: 36, Loss: 0.06732051074504852
Epoch: 36, Loss: 0.06729570031166077
Epoch: 36, Loss: 0.06727095693349838
Epoch: 36, Loss: 0.06724628806114197
Epoch: 36, Loss: 0.06722167134284973
Epoch: 36, Loss: 0.06719713658094406
Epoch: 36, Loss: 0.06717265397310257
Epoch: 36, Loss: 0.06714822351932526
Epoch: 36, Loss: 0.06712387502193451
Epoch: 36, Loss: 0.06709957867860794
Epoch: 37, Loss: 0.06707534939050674
Epoch: 37, Loss: 0.06705118715763092
Epoch: 37, Loss: 0.06702707707881927
Epoch: 37, Loss: 0.0670030415058136
Epoch: 37, Loss: 0.0669790655374527
Epoch: 37, Loss: 0.06695514172315598

# Evaluation

In [28]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.7).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5415512323379517